// Generated by CoffeeScript 1.6.3
(function() {
  var addPoint, clear, ctx, cv, getReference, listPoints, redraw, sortByAngle;

  cv = document.getElementById("canvas");

  ctx = cv.getContext("2d");

  clear = function() {
    ctx.fillStyle = "Yellow";
    return ctx.fillRect(0, 0, cv.width, cv.height);
  };

  listPoints = [[100, 100], [150, 100], [150, 55], [150, 10], [180, 100]];

  addPoint = function(x, y) {
    return listPoints.push([x, y]);
  };

  getReference = function(points) {
    return points.reduce(function(_arg, _arg1) {
      var accX, accY, x, y;
      accX = _arg[0], accY = _arg[1];
      x = _arg1[0], y = _arg1[1];
      if (y > accY || (x < accX && y === accY)) {
        return [x, y];
      } else {
        return [accX, accY];
      }
    });
  };

  sortByAngle = function(points, reference) {
    var xr, yr;
    xr = reference[0], yr = reference[1];
    return _(points).sort(function(_arg) {
      var dx, dy, hypo, x, y;
      x = _arg[0], y = _arg[1];
      dx = x - xr;
      dy = y - yr;
      hypo = Math.sqrt(dx * dx + dy * dy);
      return -dx / hypo;
    });
  };

  redraw = function() {
    var byAngle, reference, width, x, y, _i, _len, _ref, _results;
    clear();
    width = 10;
    reference = getReference(listPoints);
    byAngle = sortByAngle(listPoints, reference);
    _results = [];
    for (_i = 0, _len = listPoints.length; _i < _len; _i++) {
      _ref = listPoints[_i], x = _ref[0], y = _ref[1];
      ctx.fillStyle = _.isEqual([x, y], reference) ? "Green" : "red";
      _results.push(ctx.fillRect(x - width / 2, y - width / 2, width, width));
    }
    return _results;
  };

  redraw();

  cv.addEventListener("click", function(event) {
    addPoint(event.x - cv.offsetTop, event.y - cv.offsetLeft);
    return redraw();
  });

}).call(this);
